/**
 * Builds a fictional IBKR Flex Query XML statement from the demo fills, in the same
 * shape as a real Activity Flex report (OpenPositions, CashReport, Trades with both
 * EXECUTION and CLOSED_LOT levels). Run `npm run demo:flex` to regenerate
 * `demo/raw/ibkr-flex-sample.xml`.
 */

import { computeFifo } from "../core/fifo";
import { TableFxProvider } from "../core/fx";
import { round } from "../core/math";
import { AS_OF, IBKR_CASH, IBKR_FILLS, IBKR_FUTURE, IBKR_MARKET, YEAR_START, buildFxTable } from "./fixtures";

const ACCOUNT = "U0000000"; // placeholder account id
const ymd = (iso: string) => iso.slice(0, 10).replaceAll("-", "");
const hms = (iso: string) => iso.slice(11, 19).replaceAll(":", "");
const attrs = (o: Record<string, string | number>) =>
  Object.entries(o)
    .map(([k, v]) => `${k}="${typeof v === "number" ? String(round(v, 6)) : v}"`)
    .join(" ");

export function generateFlexXml(): string {
  const fx = new TableFxProvider(buildFxTable());
  const fxToBase = (ccy: string, date: string) => (ccy === "EUR" ? 1 : 1 / fx.rate(ccy as "USD", date));
  const fifo = computeFifo(IBKR_FILLS);
  const byId = new Map(IBKR_FILLS.map((f) => [f.id, f]));

  const positions = fifo.open.map((p) => {
    const m = IBKR_MARKET[p.ticker]!;
    const value = p.quantity * m.price;
    return `<OpenPosition ${attrs({
      accountId: ACCOUNT, currency: p.currency, fxRateToBase: fxToBase(p.currency, AS_OF), assetCategory: "STK",
      ...(m.subCategory ? { subCategory: m.subCategory } : {}), symbol: p.ticker, position: p.quantity, multiplier: 1,
      markPrice: m.price, positionValue: value, costBasisPrice: p.costBasis / p.quantity, costBasisMoney: p.costBasis,
      fifoPnlUnrealized: value - p.costBasis, reportDate: ymd(AS_OF),
    })} />`;
  });
  const f = IBKR_FUTURE;
  positions.push(
    `<OpenPosition ${attrs({
      accountId: ACCOUNT, currency: f.currency, fxRateToBase: fxToBase(f.currency, AS_OF), assetCategory: "FUT", symbol: f.symbol,
      position: f.quantity, multiplier: f.multiplier, markPrice: f.mark, positionValue: f.quantity * f.mark * f.multiplier,
      costBasisPrice: f.entry, costBasisMoney: f.quantity * f.entry * f.multiplier,
      fifoPnlUnrealized: f.quantity * (f.mark - f.entry) * f.multiplier, reportDate: ymd(AS_OF),
    })} />`,
  );

  const cash = [
    `<CashReportCurrency ${attrs({ accountId: ACCOUNT, currency: "BASE_SUMMARY", endingCash: IBKR_CASH.reduce((s, c) => s + c.endingCash * fxToBase(c.currency, AS_OF), 0) })} />`,
    ...IBKR_CASH.map((c) => `<CashReportCurrency ${attrs({ accountId: ACCOUNT, currency: c.currency, endingCash: c.endingCash })} />`),
  ];

  const realizedBySell = new Map(fifo.realized.map((r) => [r.sellFillId, r]));
  const trades: string[] = [];
  for (const fill of IBKR_FILLS) {
    const r = realizedBySell.get(fill.id);
    const base = {
      accountId: ACCOUNT, currency: fill.currency, fxRateToBase: fxToBase(fill.currency, fill.ts), assetCategory: fill.assetCategory,
      ...(fill.subCategory ? { subCategory: fill.subCategory } : {}), symbol: fill.ticker,
    };
    trades.push(
      `<Trade ${attrs({
        ...base, tradeID: fill.id, tradeDate: ymd(fill.ts), dateTime: `${ymd(fill.ts)};${hms(fill.ts)}`,
        buySell: fill.side, quantity: fill.side === "SELL" ? -fill.quantity : fill.quantity, tradePrice: fill.price,
        ibCommission: -fill.fee, fifoPnlRealized: r?.netPnl ?? 0, levelOfDetail: "EXECUTION",
      })} />`,
    );
    // One CLOSED_LOT row per lot consumed by a sell, with its share of net P&L.
    if (r && r.netPnl !== null) {
      for (const lot of r.matchedLots) {
        const buy = byId.get(lot.buyFillId)!;
        const share = lot.quantity / r.quantity;
        const lotNet = lot.quantity * (fill.price - lot.price) - fill.fee * share - (buy.fee / buy.quantity) * lot.quantity;
        trades.push(
          `<Trade ${attrs({
            ...base, tradeID: fill.id, tradeDate: ymd(fill.ts), openDateTime: `${ymd(buy.ts)};${hms(buy.ts)}`,
            buySell: "SELL", quantity: -lot.quantity, tradePrice: lot.price, ibCommission: 0, fifoPnlRealized: lotNet,
            levelOfDetail: "CLOSED_LOT",
          })} />`,
        );
      }
    }
  }

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- FICTIONAL DEMO STATEMENT — generated by demo/flex-generator.ts. Not real account data. -->
<FlexQueryResponse queryName="Demo Activity" type="AF">
<FlexStatements count="1">
<FlexStatement accountId="${ACCOUNT}" fromDate="${ymd(YEAR_START)}" toDate="${ymd(AS_OF)}" period="YearToDate" whenGenerated="${ymd(AS_OF)};220000">
<OpenPositions>
${positions.join("\n")}
</OpenPositions>
<CashReport>
${cash.join("\n")}
</CashReport>
<Trades>
${trades.join("\n")}
</Trades>
</FlexStatement>
</FlexStatements>
</FlexQueryResponse>
`;
}
